### PR TITLE
Update GNOME SDK to 3.34

### PR DESCRIPTION
**Pull request by hfiguiere**
- add intltool from shared-modules

### CODE REVIEW

**Comment by junrrein** [comment]
Hi there, thanks for the pull request!

Unfortunately, Slicer is still hitting https://github.com/flathub/flathub/issues/1078.

If nothing is done about it, I'll end up removing the submodules and just copying those dependencies in Slicer's repo.

**Comment by hfiguiere** [comment]
Failure is similar to the one of #22 - and this is not even a new version from upstream. Definitely a regression.

**Comment by junrrein** [comment]
Wait a minute, in your last build attempt the ARM build succeeded, while the others failed.

The divergence happens after:
* [For the x86_64 build](https://flathub.org/builds/#/builders/10/builds/1080): Line 120504.
* [For the ARM build](https://flathub.org/builds/#/builders/30/builds/695/steps/7/logs/stdio): Line 119423.

**Comment by bochecha** [comment]
openjpeg is already included in the GNOME 3.34 runtime, so you can remove it from this manifest when at the same time as you update.

**Comment by junrrein** [comment]
@bochecha Thanks, it's good to know that. This manifest is kinda oldish now (compared to the one in master), but once this goes through I'll make sure to remove openjpeg from the manifest.

**Comment by junrrein** [comment]
bot, build

**Comment by junrrein** [comment]
This has been superseded by https://github.com/flathub/com.github.junrrein.PDFSlicer/pull/24.

**Pull request closed without merging**
